version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: medical-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB_NAME=${MONGODB_DB_NAME}
      - NODE_ENV=production
      - FRONTEND_URL=${FRONTEND_URL}
    volumes:
      - ./backend/uploads:/app/uploads
    restart: unless-stopped
    networks:
      - medical-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: medical-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - medical-network

networks:
  medical-network:
    driver: bridge

volumes:
  uploads:
