services:
  - type: web
    name: online-medical-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        value: online_medical
      - key: FRONTEND_URL
        sync: false
